app/routes.php
<?php

# ------------------ Route patterns---------------------
Route::pattern('id', '[0-9]+');

# ------------------ Page Route ------------------------

Route::get('/', [
    'as' => 'home',
    'uses' => 'PagesController@home',
]);

Route::get('/about', [
    'as' => 'about',
    'uses' => 'PagesController@about',
]);

Route::get('/wiki', [
    'as' => 'wiki',
    'uses' => 'PagesController@wiki',
]);

Route::get('/search', [
    'as' => 'search',
    'uses' => 'PagesController@search',
]);

Route::get('/feed', [
    'as' => 'feed',
    'uses' => 'PagesController@feed',
]);

Route::get('/sitemap', 'PagesController@sitemap');
Route::get('/sitemap.xml', 'PagesController@sitemap');

# ------------------ User stuff ------------------------

Route::get('/users/{id}/replies', [
    'as' => 'users.replies',
    'uses' => 'UsersController@replies',
]);

Route::get('/users/{id}/topics', [
    'as' => 'users.topics',
    'uses' => 'UsersController@topics',
]);

Route::get('/users/{id}/favorites', [
    'as' => 'users.favorites',
    'uses' => 'UsersController@favorites',
]);

Route::get('/users/{id}/refresh_cache', [
    'as' => 'users.refresh_cache',
    'uses' => 'UsersController@refreshCache',
]);

Route::get('/users/{id}/access_tokens', [
    'as' => 'users.access_tokens',
    'uses' => 'UsersController@accessTokens',
]);

Route::get('/access_token/{token}/revoke', [
    'as' => 'users.access_tokens.revoke',
    'uses' => 'UsersController@revokeAccessToken',
]);

Route::get('users/regenerate_login_token', [
    'as' => 'users.regenerate_login_token',
    'uses' => 'UsersController@regenerateLoginToken',
]);

Route::post('/favorites/{id}', [
    'as' => 'favorites.createOrDelete',
    'uses' => 'FavoritesController@createOrDelete',
    'before' => 'auth',
]);

Route::get('/notifications', [
    'as' => 'notifications.index',
    'uses' => 'NotificationsController@index',
    'before' => 'auth',
]);

Route::get('/notifications/count', [
    'as' => 'notifications.count',
    'uses' => 'NotificationsController@count',
    'before' => 'auth',
]);

Route::post('/attentions/{id}', [
    'as' => 'attentions.createOrDelete',
    'uses' => 'AttentionsController@createOrDelete',
    'before' => 'auth',
]);

# ------------------ Authentication ------------------------

Route::get('login', [
    'as' => 'login',
    'uses' => 'AuthController@login',
]);

Route::get('login-required', [
    'as' => 'login-required',
    'uses' => 'AuthController@loginRequired',
]);

Route::get('admin-required', [
    'as' => 'admin-required',
    'uses' => 'AuthController@adminRequired',
]);

Route::get('user-banned', [
    'as' => 'user-banned',
    'uses' => 'AuthController@userBanned',
]);

Route::get('signup', [
    'as' => 'signup',
    'uses' => 'AuthController@create',
]);

Route::post('signup',  [
    'as' => 'signup',
    'uses' => 'AuthController@store',
]);

Route::get('logout', [
    'as' => 'logout',
    'uses' => 'AuthController@logout',
]);

Route::get('oauth', 'AuthController@getOauth');

# ------------------ Resource Route ------------------------

Route::resource('nodes', 'NodesController', ['except' => ['index', 'edit']]);
Route::resource('topics', 'TopicsController');
Route::resource('votes', 'VotesController');
Route::resource('users', 'UsersController');

# ------------------ Replies ------------------------

Route::resource('replies', 'RepliesController', ['only' => ['store']]);
Route::delete('replies/delete/{id}',  [
    'as' => 'replies.destroy',
    'uses' => 'RepliesController@destroy',
    'before' => 'auth',
]);

# ------------------ Votes ------------------------

Route::group(['before' => 'auth'], function () {
    Route::post('/topics/{id}/upvote', [
        'as' => 'topics.upvote',
        'uses' => 'TopicsController@upvote',
    ]);

    Route::post('/topics/{id}/downvote', [
        'as' => 'topics.downvote',
        'uses' => 'TopicsController@downvote',
    ]);

    Route::post('/replies/{id}/vote', [
        'as' => 'replies.vote',
        'uses' => 'RepliesController@vote',
    ]);

    Route::post('/topics/{id}/append', [
        'as' => 'topics.append',
        'uses' => 'TopicsController@append',
    ]);
});

# ------------------ Admin Route ------------------------

Route::group(['before' => 'manage_topics'], function () {
    Route::post('topics/recomend/{id}',  [
        'as' => 'topics.recomend',
        'uses' => 'TopicsController@recomend',
    ]);

    Route::post('topics/wiki/{id}',  [
        'as' => 'topics.wiki',
        'uses' => 'TopicsController@wiki',
    ]);

    Route::post('topics/pin/{id}',  [
        'as' => 'topics.pin',
        'uses' => 'TopicsController@pin',
    ]);

    Route::delete('topics/delete/{id}',  [
        'as' => 'topics.destroy',
        'uses' => 'TopicsController@destroy',
    ]);

    Route::post('topics/sink/{id}',  [
        'as' => 'topics.sink',
        'uses' => 'TopicsController@sink',
    ]);
});

Route::group(['before' => 'manage_users'], function () {
    Route::post('users/blocking/{id}',  [
        'as' => 'users.blocking',
        'uses' => 'UsersController@blocking',
    ]);
});

Route::post('upload_image', [
    'as' => 'upload_image',
    'uses' => 'TopicsController@uploadImage',
    'before' => 'auth',
]);

// Health Checking
Route::get('heartbeat', function () {
    return Node::first();
});

Route::get('/github-api-proxy/users/{username}', [
    'as' => 'users.github-api-proxy',
    'uses' => 'UsersController@githubApiProxy',
]);

Route::get('/github-card', [
    'as' => 'users.github-card',
    'uses' => 'UsersController@githubCard',
]);

app/controllers/TopicsController.php
<?php

use Phphub\Core\CreatorListener;
use Phphub\Forms\TopicCreationForm;

class TopicsController extends \BaseController implements CreatorListener
{
    protected $topic;

    public function __construct(Topic $topic)
    {
        parent::__construct();

        $this->beforeFilter('auth', ['except' => ['index', 'show']]);
        $this->topic = $topic;
    }

    public function index()
    {
        $filter = $this->topic->present()->getTopicFilter();
        $topics = $this->topic->getTopicsWithFilter($filter);
        $nodes  = Node::allLevelUp();
        $links  = Link::remember(1440)->get();

        return View::make('topics.index', compact('topics', 'nodes', 'links'));
    }

    public function create()
    {
        $node = Node::find(Input::get('node_id'));
        $nodes = Node::allLevelUp();

        return View::make('topics.create_edit', compact('nodes', 'node'));
    }

    public function store()
    {
        return App::make('Phphub\Creators\TopicCreator')->create($this, Input::except('_token'));
    }

    public function show($id)
    {
        $topic = Topic::findOrFail($id);
        $replies = $topic->getRepliesWithLimit(Config::get('phphub.replies_perpage'));
        $node = $topic->node;
        $nodeTopics = $topic->getSameNodeTopics();

        $topic->increment('view_count', 1);

        return View::make('topics.show', compact('topic', 'replies', 'nodeTopics', 'node'));
    }

    public function edit($id)
    {
        $topic = Topic::findOrFail($id);
        $this->authorOrAdminPermissioinRequire($topic->user_id);
        $nodes = Node::allLevelUp();
        $node = $topic->node;

        $topic->body = $topic->body_original;

        return View::make('topics.create_edit', compact('topic', 'nodes', 'node'));
    }

    public function append($id)
    {
        $topic = Topic::findOrFail($id);
        $this->authorOrAdminPermissioinRequire($topic->user_id);

        $markdown = new Markdown;
        $content = $markdown->convertMarkdownToHtml(Input::get('content'));

        $append = Append::create(['topic_id' => $topic->id, 'content' => $content]);

        App::make('Phphub\Notification\Notifier')->newAppendNotify(Auth::user(), $topic, $append);

        Flash::success(lang('Operation succeeded.'));
        return Redirect::route('topics.show', $topic->id);
    }

    public function update($id)
    {
        $topic = Topic::findOrFail($id);
        $data = Input::only('title', 'body', 'node_id');

        $this->authorOrAdminPermissioinRequire($topic->user_id);

        $markdown = new Markdown;
        $data['body_original'] = $data['body'];
        $data['body'] = $markdown->convertMarkdownToHtml($data['body']);
        $data['excerpt'] = Topic::makeExcerpt($data['body']);

        // Validation
        App::make('Phphub\Forms\TopicCreationForm')->validate($data);

        $topic->update($data);

        Flash::success(lang('Operation succeeded.'));
        return Redirect::route('topics.show', $topic->id);
    }

    /**
     * ----------------------------------------
     * User Topic Vote function
     * ----------------------------------------
     */

    public function upvote($id)
    {
        $topic = Topic::find($id);
        App::make('Phphub\Vote\Voter')->topicUpVote($topic);
        return Redirect::route('topics.show', $topic->id);
    }

    public function downvote($id)
    {
        $topic = Topic::find($id);
        App::make('Phphub\Vote\Voter')->topicDownVote($topic);
        return Redirect::route('topics.show', $topic->id);
    }

    /**
     * ----------------------------------------
     * Admin Topic Management
     * ----------------------------------------
     */

    public function recomend($id)
    {
        $topic = Topic::findOrFail($id);
        $this->authorOrAdminPermissioinRequire($topic->user_id);
        $topic->is_excellent = (!$topic->is_excellent);
        $topic->save();
        Flash::success(lang('Operation succeeded.'));
        Notification::notify('topic_mark_excellent', Auth::user(), $topic->user, $topic);
        return Redirect::route('topics.show', $topic->id);
    }

    public function wiki($id)
    {
        $topic = Topic::findOrFail($id);
        $this->authorOrAdminPermissioinRequire($topic->user_id);
        $topic->is_wiki = (!$topic->is_wiki);
        $topic->save();
        Flash::success(lang('Operation succeeded.'));
        Notification::notify('topic_mark_wiki', Auth::user(), $topic->user, $topic);
        return Redirect::route('topics.show', $topic->id);
    }

    public function pin($id)
    {
        $topic = Topic::findOrFail($id);
        $this->authorOrAdminPermissioinRequire($topic->user_id);
        ($topic->order > 0) ? $topic->decrement('order', 1) : $topic->increment('order', 1);
        return Redirect::route('topics.show', $topic->id);
    }

    public function sink($id)
    {
        $topic = Topic::findOrFail($id);
        $this->authorOrAdminPermissioinRequire($topic->user_id);
        ($topic->order >= 0) ? $topic->decrement('order', 1) : $topic->increment('order', 1);
        return Redirect::route('topics.show', $topic->id);
    }

    public function destroy($id)
    {
        $topic = Topic::findOrFail($id);
        $this->authorOrAdminPermissioinRequire($topic->user_id);
        $topic->delete();
        Flash::success(lang('Operation succeeded.'));

        return Redirect::route('topics.index');
    }

    public function uploadImage()
    {
        if ($file = Input::file('file')) {
            $allowed_extensions = ["png", "jpg", "gif"];
            if ($file->getClientOriginalExtension() && !in_array($file->getClientOriginalExtension(), $allowed_extensions)) {
                return ['error' => 'You may only upload png, jpg or gif.'];
            }

            $fileName        = $file->getClientOriginalName();
            $extension       = $file->getClientOriginalExtension() ?: 'png';
            $folderName      = 'uploads/images/' . date("Ym", time()) .'/'.date("d", time()) .'/'. Auth::user()->id;
            $destinationPath = public_path() . '/' . $folderName;
            $safeName        = str_random(10).'.'.$extension;
            $file->move($destinationPath, $safeName);

            // If is not gif file, we will try to reduse the file size
            if ($file->getClientOriginalExtension() != 'gif') {
                // open an image file
                $img = Image::make($destinationPath . '/' . $safeName);
                // prevent possible upsizing
                $img->resize(1440, null, function ($constraint) {
                    $constraint->aspectRatio();
                    $constraint->upsize();
                });
                // finally we save the image as a new file
                $img->save();
            }

            $data['filename'] = getUserStaticDomain() . $folderName .'/'. $safeName;

            SiteStatus::newImage();
        } else {
            $data['error'] = 'Error while uploading file';
        }
        return $data;
    }

    /**
     * ----------------------------------------
     * CreatorListener Delegate
     * ----------------------------------------
     */

    public function creatorFailed($errors)
    {
        return Redirect::to('/');
    }

    public function creatorSucceed($topic)
    {
        Flash::success(lang('Operation succeeded.'));

        return Redirect::route('topics.show', array($topic->id));
    }
}

app/views/topics/partials/body.blade.php
<div class="markdown-body" id="emojify">
{{ $body }}
</div>

app/views/topics/partials/composing_help_block.blade.php
<div id="reply_notice" class="box" style="display:none">
    <ul class="helpblock list">
      <li>{{ lang('publish_typography') }}</li>
      <li>{{ lang('publish_markdown') }}</li>
      <li>{{ lang('publish_emoji') }}</li>
      <li>{{ lang('publish_at_user') }}</li>
      <li>{{ lang('publish_image') }}</li>
    </ul>
</div>

app/views/topics/partials/filter.blade.php
<ul class="pull-right list-inline remove-margin-bottom topic-filter">

    <li>
        <a {{ App::make('Topic')->present()->topicFilter('recent') }}>
            <i class="glyphicon glyphicon-time"></i> {{ lang('Recent') }}
        </a>
        <span class="divider"></span>
    </li>

    <li>
        <a {{ App::make('Topic')->present()->topicFilter('excellent') }}>
            <i class="glyphicon glyphicon-ok"> </i> {{ lang('Excellent') }}
        </a>
        <span class="divider"></span>
    </li>

    <li>
        <a {{ App::make('Topic')->present()->topicFilter('vote') }}>
            <i class="glyphicon glyphicon-thumbs-up"> </i> {{ lang('Vote') }}
        </a>
        <span class="divider"></span>
    </li>

    <li>
        <a {{ App::make('Topic')->present()->topicFilter('noreply') }}>
            <i class="glyphicon glyphicon-eye-open"></i> {{ lang('Noreply') }}
        </a>
    </li>
</ul>

app/views/topics/partials/meta.blade.php
<div class="meta inline-block" >

  <a href="{{ route('nodes.show', $topic->node->id) }}" class="remove-padding-left">
    {{{ $topic->node->name }}}
  </a>
  •
  <a href="{{ route('users.show', $topic->user->id) }}">
    {{{ $topic->user->name }}}
  </a>

  @if ($topic->user->present()->hasBadge())
    <span class="label label-warning" style="position: relative;">{{{ $topic->user->present()->badgeName() }}}</span>
  @endif
  •
  {{ lang('at') }} <abbr title="{{ $topic->created_at }}" class="timeago">{{ $topic->created_at }}</abbr>
  •

  @if (count($topic->lastReplyUser))
    {{ lang('Last Reply by') }}
      <a href="{{{ URL::route('users.show', [$topic->lastReplyUser->id]) }}}">
        {{{ $topic->lastReplyUser->name }}}
      </a>
     {{ lang('at') }} <abbr title="{{ $topic->updated_at }}" class="timeago">{{ $topic->updated_at }}</abbr>
    •
  @endif

  {{ $topic->view_count }} {{ lang('Reads') }}
</div>
<div class="clearfix"></div>

app/views/topics/partials/replies.blade.php
<ul class="list-group row">

  @foreach ($replies as $index => $reply)
   <li class="list-group-item media"
           @if($reply->vote_count >= 2)
                style="margin-top: 0px; background-color: #fffce9"
           @else
                style="margin-top: 0px;"
           @endif
           >

    <div class="avatar pull-left">
      <a href="{{ route('users.show', [$reply->user_id]) }}">
        <img class="media-object img-thumbnail avatar" alt="{{{ $reply->user->name }}}" src="{{ $reply->user->present()->gravatar }}"  style="width:48px;height:48px;"/>
      </a>
    </div>

    <div class="infos">

      <div class="media-heading meta">

        <a href="{{ route('users.show', [$reply->user_id]) }}" title="{{{ $reply->user->name }}}" class="remove-padding-left author">
            {{{ $reply->user->name }}}
        </a>

        <span> •  </span>
        <abbr class="timeago" title="{{ $reply->created_at }}">{{ $reply->created_at }}</abbr>
        <span> •  </span>
        <a name="reply{{ $topic->present()->replyFloorFromIndex($index) }}" class="anchor" href="#reply{{ $topic->present()->replyFloorFromIndex($index) }}" aria-hidden="true">#{{ $topic->present()->replyFloorFromIndex($index) }}</a>

        <span class="operate pull-right">
          <a data-method="post" id="reply-up-vote-{{ $reply->id }}" href="javascript:void(0);" data-url="{{ route('replies.vote', $reply->id) }}" title="{{ lang('Vote Up') }}">
             <i class="fa fa-thumbs-o-up" style="font-size:14px;"></i> {{ $reply->vote_count ?: '' }}
          </a>
          <span> •  </span>

          @if ($currentUser && ($currentUser->can("manage_topics") || $currentUser->id == $reply->user_id) )
            <a id="reply-delete-{{ $reply->id }}" data-method="delete"  href="javascript:void(0);" data-url="{{ route('replies.destroy', [$reply->id]) }}" title="{{ lang('Delete') }}">
                <i class="fa fa-trash-o"></i>
            </a>
            <span> •  </span>
          @endif
          <a class="fa fa-reply" href="javascript:void(0)" onclick="replyOne('{{{ $reply->user->name }}}');" title="回复 {{{ $reply->user->name }}}"></a>
        </span>

      </div>

      <div class="media-body markdown-reply content-body">
{{ $reply->body }}
      </div>

    </div>

  </li>
  @endforeach

</ul>

app/views/topics/partials/ribbon.blade.php
@if ($topic->is_excellent || $topic->is_wiki)
  <div class="ribbon">
    @if ($topic->is_excellent)
      <div class="ribbon-excellent">
          <i class="fa fa-trophy"></i> {{ lang('This topic has been mark as Excenllent Topic.') }}
      </div>
    @endif

    @if ($topic->is_wiki)
      <div class="ribbon-wiki">
          <i class="fa fa-graduation-cap"></i> {{ lang('This is a Community Wiki.') }}
      </div>
    @endif
  </div>
@endif

app/views/topics/partials/topic_operate.blade.php
<div class="panel-footer operate">

  <div class="pull-left" style="font-size:15px;">
    <a class="" href="http://service.weibo.com/share/share.php?url={{ urlencode(Request::url()) }}&type=3&pic=&title={{{ $topic->title }}}" target="_blank" title="{{ lang('Share on Weibo') }}">
      <i class="fa fa-weibo"></i>
    </a>
    <a href="https://twitter.com/intent/tweet?url={{ urlencode(Request::url()) }}&text={{{ $topic->title }}}&via=phphub.org" class=""  target="_blank" title="{{ lang('Share on Twitter') }}">
      <i class="fa fa-twitter"></i>
    </a>
    <a href="http://www.facebook.com/sharer.php?u={{ urlencode(Request::url()) }}" class=""  target="_blank" title="{{ lang('Share on Facebook') }}">
      <i class="fa fa-facebook"></i>
    </a>
    <a href="https://plus.google.com/share?url={{ urlencode(Request::url()) }}" class=""  target="_blank" title="{{ lang('Share on Google Plus') }}">
      <i class="fa fa-google-plus"></i>
    </a>
  </div>

  <div class="pull-right">

    @if ($currentUser && Attention::isUserAttentedTopic($currentUser, $topic))
      <a data-method="post" id="topic-attent-cancel-button" href="javascript:void(0);" data-url="{{ route('attentions.createOrDelete', $topic->id) }}">
        <i class="glyphicon glyphicon-eye-open" style="color:#ce8a81"></i> <span>{{ lang('Cancel') }}</span>
      </a>
    @else
      <a data-method="post" id="topic-attent-button" href="javascript:void(0);" data-url="{{ route('attentions.createOrDelete', $topic->id) }}">
        <i class="glyphicon glyphicon-eye-open"></i> <span>{{ lang('Attent') }}</span>
      </a>
    @endif

    @if ($currentUser && Favorite::isUserFavoritedTopic($currentUser, $topic))
      <a data-method="post" id="topic-favorite-cancel-button" href="javascript:void(0);" data-url="{{ route('favorites.createOrDelete', $topic->id) }}">
        <i class="glyphicon glyphicon-bookmark" style="color:#ce8a81"></i> <span>{{ lang('Cancel') }}</span>
      </a>
    @else
      <a data-method="post" id="topic-favorite-button" href="javascript:void(0);" data-url="{{ route('favorites.createOrDelete', $topic->id) }}">
        <i class="glyphicon glyphicon-bookmark"></i> <span>{{ lang('Favorite') }}</span>
      </a>
    @endif

    @if ($currentUser && $currentUser->can("manage_topics") )
        <a data-method="post" id="topic-recomend-button" href="javascript:void(0);" data-url="{{ route('topics.recomend', [$topic->id]) }}" class="admin {{ $topic->is_excellent ? 'active' :'';}}" title="{{ lang('Mark as Excellent') }}">
        <i class="fa fa-trophy"></i>
        </a>

        <a data-method="post" id="topic-wiki-button" href="javascript:void(0);" data-url="{{ route('topics.wiki', [$topic->id]) }}" class="admin {{ $topic->is_wiki ? 'active' : '' }}" title="{{ lang('Mark as Community Wiki') }}">
        <i class="fa fa-graduation-cap"></i>
        </a>

        @if ($topic->order >= 0)
          <a data-method="post" id="topic-pin-button" href="javascript:void(0);" data-url="{{ route('topics.pin', [$topic->id]) }}" class="admin {{ $topic->order > 0 ? 'active' : '' }}" title="{{ lang('Pin it on Top') }}">
            <i class="fa fa-thumb-tack"></i>
          </a>
        @endif

        @if ($topic->order <= 0)
            <a data-method="post" id="topic-sink-button" href="javascript:void(0);" data-url="{{ route('topics.sink', [$topic->id]) }}" class="admin {{ $topic->order < 0 ? 'active' : '' }}" title="{{ lang('Sink This Topic') }}">
                <i class="fa fa-anchor"></i>
            </a>
        @endif

        <a data-method="delete" id="topic-delete-button" href="javascript:void(0);" data-url="{{ route('topics.destroy', [$topic->id]) }}" title="{{ lang('Delete') }}" class="admin">
            <i class="fa fa-trash-o"></i>
        </a>
    @endif

    @if ( $currentUser && ($currentUser->can("manage_topics") || $currentUser->id == $topic->user_id) )
      <a id="topic-append-button" href="javascript:void(0);" title="{{ lang('Append') }}" class="admin" data-toggle="modal" data-target="#exampleModal">
        <i class="fa fa-plus"></i>
      </a>

      <a id="topic-edit-button" href="{{ route('topics.edit', [$topic->id]) }}" title="{{ lang('Edit') }}" class="admin">
        <i class="fa fa-pencil-square-o"></i>
      </a>
    @endif

  </div>
  <div class="clearfix"></div>
</div>


<div class="modal fade" id="exampleModal" tabindex="-1" role="" aria-labelledby="exampleModalLabel" >
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">{{ lang('Append Content') }}</h4>
      </div>

     {{ Form::open(['route' => ['topics.append', $topic->id],'method' => 'post']) }}

        <div class="modal-body">

          <div class="alert alert-warning">
              {{ lang('append_notice') }}
          </div>

          <div class="form-group">
            {{ Form::textarea('content', null, ['class' => 'form-control',
                                                'style' => 'min-height:20px',
                                          'placeholder' => lang('Please using markdown.')]) }}

          </div>

          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">{{ lang('Close') }}</button>
            <button type="submit" class="btn btn-primary">{{ lang('Submit') }}</button>
          </div>

      {{ Form::close() }}

    </div>
  </div>
</div>

app/views/topics/partials/topics.blade.php
@if (count($topics))

<ul class="list-group row topic-list">
    @foreach ($topics as $topic)
     <li class="list-group-item media {{ !$column ?:'col-sm-6'; }}" style="margin-top: 0px;">

        <a class="pull-right" href="{{ route('topics.show', [$topic->id]) }}" >
            <span class="badge badge-reply-count"> {{ $topic->reply_count }} </span>
        </a>

        <div class="avatar pull-left">
            <a href="{{ route('users.show', [$topic->user_id]) }}">
                <img class="media-object img-thumbnail avatar" alt="{{{ $topic->user->name }}}" src="{{ $topic->user->present()->gravatar }}"  style="width:48px;height:48px;"/>
            </a>
        </div>

        <div class="infos">

          <div class="media-heading">

            @if ($topic->order > 0 && !Input::get('filter') && Route::currentRouteName() != 'home' )
                <span class="label label-warning">{{ lang('Stick') }}</span>
            @elseif ($topic->is_excellent && !Input::get('filter') && Route::currentRouteName() != 'home' )
                <span class="label label-success">{{ lang('Recommended') }}</span>
            @endif

            <a href="{{ route('topics.show', [$topic->id]) }}" title="{{{ $topic->title }}}">
                {{{ $topic->title }}}
            </a>
          </div>
          <div class="media-body meta">

            @if ($topic->vote_count > 0)
                <a href="{{ route('topics.show', [$topic->id]) }}" class="remove-padding-left" id="pin-{{ $topic->id }}">
                    <span class="fa fa-thumbs-o-up"> {{ $topic->vote_count }} </span>
                </a>
                <span> •  </span>
            @endif

            <a href="{{ route('nodes.show', [$topic->node->id]) }}" title="{{{ $topic->node->name }}}" {{ $topic->vote_count == 0 || 'class="remove-padding-left"'}}>
                {{{ $topic->node->name }}}
            </a>

            @if ($topic->reply_count == 0)
                <span> • </span>
                <a href="{{ route('users.show', [$topic->user_id]) }}" title="{{{ $topic->user->name }}}">
                    {{{ $topic->user->name }}}
                </a>
                <span> • </span>
                <span class="timeago">{{ $topic->created_at }}</span>
            @endif

            @if ($topic->reply_count > 0 && count($topic->lastReplyUser))
                <span> • </span>{{ lang('Last Reply by') }}
                <a href="{{{ URL::route('users.show', [$topic->lastReplyUser->id]) }}}">
                  {{{ $topic->lastReplyUser->name }}}
                </a>
                <span> • </span>
                <span class="timeago">{{ $topic->updated_at }}</span>
            @endif
          </div>

        </div>

    </li>
    @endforeach
</ul>

@else
   <div class="empty-block">{{ lang('Dont have any data Yet') }}~~</div>
@endif